import { CountryConfig } from '@/types/country';

export const COUNTRY_PRESETS: Record<string, CountryConfig> = {
  US: {
    name: 'United States',
    code: 'US',
    currency: 'USD',
    taxSystem: {
      type: 'SalesTax',
      rates: {
        federal: 0,
        state: {
          default: 0,
          // Add state-specific rates
        }
      },
      filingFrequency: 'quarterly',
      vatThreshold: 0
    },
    accounting: {
      standard: 'GAAP',
      fiscalYearStart: '01-01',
      reportingPeriods: ['monthly', 'quarterly', 'annual']
    },
    banking: {
      methods: ['ACH', 'Wire', 'Check'],
      defaultCurrency: 'USD',
      supportedCurrencies: ['USD']
    },
    reportingTemplates: [
      'Income Statement',
      'Balance Sheet',
      'Cash Flow Statement',
      '1099',
      'W-2',
      'Sales Tax Return'
    ],
    timezone: 'America/New_York',
    dateFormat: 'MM/DD/YYYY',
    numberFormat: {
      decimal: '.',
      thousands: ',',
      precision: 2
    }
  },
  GB: {
    name: 'United Kingdom',
    code: 'GB',
    currency: 'GBP',
    taxSystem: {
      type: 'VAT',
      rates: {
        standard: 0.20,
        reduced: 0.05,
        zero: 0
      },
      filingFrequency: 'quarterly',
      vatThreshold: 85000
    },
    accounting: {
      standard: 'IFRS',
      fiscalYearStart: '04-01',
      reportingPeriods: ['monthly', 'quarterly', 'annual']
    },
    banking: {
      methods: ['BACS', 'Faster Payments', 'CHAPS'],
      defaultCurrency: 'GBP',
      supportedCurrencies: ['GBP', 'EUR', 'USD']
    },
    reportingTemplates: [
      'VAT Return',
      'Corporation Tax Return',
      'Annual Accounts',
      'P11D',
      'P60'
    ],
    timezone: 'Europe/London',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: {
      decimal: '.',
      thousands: ',',
      precision: 2
    }
  },
  KE: {
    name: 'Kenya',
    code: 'KE',
    currency: 'KES',
    taxSystem: {
      type: 'VAT',
      rates: {
        standard: 0.16,
        zero: 0
      },
      filingFrequency: 'monthly',
      vatThreshold: 5000000
    },
    accounting: {
      standard: 'IFRS',
      fiscalYearStart: '01-01',
      reportingPeriods: ['monthly', 'quarterly', 'annual']
    },
    banking: {
      methods: ['M-Pesa', 'Bank Transfer', 'Cheque'],
      defaultCurrency: 'KES',
      supportedCurrencies: ['KES', 'USD', 'EUR', 'GBP']
    },
    reportingTemplates: [
      'VAT Return',
      'Income Tax Return',
      'Annual Financial Statements',
      'PAYE Return'
    ],
    timezone: 'Africa/Nairobi',
    dateFormat: 'DD/MM/YYYY',
    numberFormat: {
      decimal: '.',
      thousands: ',',
      precision: 2
    }
  },
  // Add more countries as needed
};

export const DEFAULT_COUNTRY = 'US';

export const getCountryConfig = (countryCode: string): CountryConfig => {
  return COUNTRY_PRESETS[countryCode] || COUNTRY_PRESETS[DEFAULT_COUNTRY];
};

// Static list of all countries with code, name, and currency
// Source: ISO 3166-1 alpha-2, official names, and main currency
export const countries = [
  { code: 'US', name: 'United States', currency: 'USD' },
  { code: 'GB', name: 'United Kingdom', currency: 'GBP' },
  { code: 'CA', name: 'Canada', currency: 'CAD' },
  { code: 'AU', name: 'Australia', currency: 'AUD' },
  { code: 'DE', name: 'Germany', currency: 'EUR' },
  { code: 'FR', name: 'France', currency: 'EUR' },
  { code: 'IT', name: 'Italy', currency: 'EUR' },
  { code: 'ES', name: 'Spain', currency: 'EUR' },
  { code: 'CN', name: 'China', currency: 'CNY' },
  { code: 'JP', name: 'Japan', currency: 'JPY' },
  { code: 'IN', name: 'India', currency: 'INR' },
  { code: 'BR', name: 'Brazil', currency: 'BRL' },
  { code: 'ZA', name: 'South Africa', currency: 'ZAR' },
  { code: 'KE', name: 'Kenya', currency: 'KES' },
  { code: 'NG', name: 'Nigeria', currency: 'NGN' },
  { code: 'RU', name: 'Russia', currency: 'RUB' },
  { code: 'MX', name: 'Mexico', currency: 'MXN' },
  { code: 'KR', name: 'South Korea', currency: 'KRW' },
  { code: 'TR', name: 'Turkey', currency: 'TRY' },
  { code: 'AR', name: 'Argentina', currency: 'ARS' },
  { code: 'EG', name: 'Egypt', currency: 'EGP' },
  { code: 'SA', name: 'Saudi Arabia', currency: 'SAR' },
  { code: 'SG', name: 'Singapore', currency: 'SGD' },
  { code: 'SE', name: 'Sweden', currency: 'SEK' },
  { code: 'CH', name: 'Switzerland', currency: 'CHF' },
  { code: 'NL', name: 'Netherlands', currency: 'EUR' },
  { code: 'BE', name: 'Belgium', currency: 'EUR' },
  { code: 'PL', name: 'Poland', currency: 'PLN' },
  { code: 'UA', name: 'Ukraine', currency: 'UAH' },
  { code: 'NO', name: 'Norway', currency: 'NOK' },
  { code: 'DK', name: 'Denmark', currency: 'DKK' },
  { code: 'FI', name: 'Finland', currency: 'EUR' },
  { code: 'IE', name: 'Ireland', currency: 'EUR' },
  { code: 'AT', name: 'Austria', currency: 'EUR' },
  { code: 'GR', name: 'Greece', currency: 'EUR' },
  { code: 'PT', name: 'Portugal', currency: 'EUR' },
  { code: 'IL', name: 'Israel', currency: 'ILS' },
  { code: 'NZ', name: 'New Zealand', currency: 'NZD' },
  { code: 'TH', name: 'Thailand', currency: 'THB' },
  { code: 'ID', name: 'Indonesia', currency: 'IDR' },
  { code: 'MY', name: 'Malaysia', currency: 'MYR' },
  { code: 'PH', name: 'Philippines', currency: 'PHP' },
  { code: 'PK', name: 'Pakistan', currency: 'PKR' },
  { code: 'BD', name: 'Bangladesh', currency: 'BDT' },
  { code: 'VN', name: 'Vietnam', currency: 'VND' },
  { code: 'CL', name: 'Chile', currency: 'CLP' },
  { code: 'CO', name: 'Colombia', currency: 'COP' },
  { code: 'PE', name: 'Peru', currency: 'PEN' },
  { code: 'CZ', name: 'Czech Republic', currency: 'CZK' },
  { code: 'HU', name: 'Hungary', currency: 'HUF' },
  { code: 'RO', name: 'Romania', currency: 'RON' },
  { code: 'SK', name: 'Slovakia', currency: 'EUR' },
  { code: 'BG', name: 'Bulgaria', currency: 'BGN' },
  { code: 'HR', name: 'Croatia', currency: 'EUR' },
  { code: 'SI', name: 'Slovenia', currency: 'EUR' },
  { code: 'RS', name: 'Serbia', currency: 'RSD' },
  { code: 'MA', name: 'Morocco', currency: 'MAD' },
  { code: 'DZ', name: 'Algeria', currency: 'DZD' },
  { code: 'TN', name: 'Tunisia', currency: 'TND' },
  { code: 'GH', name: 'Ghana', currency: 'GHS' },
  { code: 'ET', name: 'Ethiopia', currency: 'ETB' },
  { code: 'TZ', name: 'Tanzania', currency: 'TZS' },
  { code: 'UG', name: 'Uganda', currency: 'UGX' },
  { code: 'CM', name: 'Cameroon', currency: 'XAF' },
  { code: 'SN', name: 'Senegal', currency: 'XOF' },
  { code: 'CI', name: "Côte d'Ivoire", currency: 'XOF' },
  { code: 'SD', name: 'Sudan', currency: 'SDG' },
  { code: 'AO', name: 'Angola', currency: 'AOA' },
  { code: 'MZ', name: 'Mozambique', currency: 'MZN' },
  { code: 'ZW', name: 'Zimbabwe', currency: 'ZWL' },
  { code: 'BW', name: 'Botswana', currency: 'BWP' },
  { code: 'NA', name: 'Namibia', currency: 'NAD' },
  { code: 'LS', name: 'Lesotho', currency: 'LSL' },
  { code: 'SZ', name: 'Eswatini', currency: 'SZL' },
  { code: 'MW', name: 'Malawi', currency: 'MWK' },
  { code: 'ZM', name: 'Zambia', currency: 'ZMW' },
  { code: 'RW', name: 'Rwanda', currency: 'RWF' },
  { code: 'BJ', name: 'Benin', currency: 'XOF' },
  { code: 'BF', name: 'Burkina Faso', currency: 'XOF' },
  { code: 'ML', name: 'Mali', currency: 'XOF' },
  { code: 'NE', name: 'Niger', currency: 'XOF' },
  { code: 'TG', name: 'Togo', currency: 'XOF' },
  { code: 'GW', name: 'Guinea-Bissau', currency: 'XOF' },
  { code: 'GM', name: 'Gambia', currency: 'GMD' },
  { code: 'SL', name: 'Sierra Leone', currency: 'SLL' },
  { code: 'LR', name: 'Liberia', currency: 'LRD' },
  { code: 'CF', name: 'Central African Republic', currency: 'XAF' },
  { code: 'CG', name: 'Congo', currency: 'XAF' },
  { code: 'GA', name: 'Gabon', currency: 'XAF' },
  { code: 'GQ', name: 'Equatorial Guinea', currency: 'XAF' },
  { code: 'ST', name: 'Sao Tome and Principe', currency: 'STN' },
  { code: 'TD', name: 'Chad', currency: 'XAF' },
  { code: 'CD', name: 'Democratic Republic of the Congo', currency: 'CDF' },
  { code: 'SO', name: 'Somalia', currency: 'SOS' },
  { code: 'DJ', name: 'Djibouti', currency: 'DJF' },
  { code: 'ER', name: 'Eritrea', currency: 'ERN' },
  { code: 'MG', name: 'Madagascar', currency: 'MGA' },
  { code: 'MU', name: 'Mauritius', currency: 'MUR' },
  { code: 'SC', name: 'Seychelles', currency: 'SCR' },
  { code: 'KM', name: 'Comoros', currency: 'KMF' },
  { code: 'CV', name: 'Cabo Verde', currency: 'CVE' },
  { code: 'SZ', name: 'Eswatini', currency: 'SZL' },
  { code: 'RE', name: 'Réunion', currency: 'EUR' },
  { code: 'YT', name: 'Mayotte', currency: 'EUR' },
  { code: 'MQ', name: 'Martinique', currency: 'EUR' },
  { code: 'GP', name: 'Guadeloupe', currency: 'EUR' },
  { code: 'GF', name: 'French Guiana', currency: 'EUR' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', currency: 'EUR' },
  { code: 'BL', name: 'Saint Barthélemy', currency: 'EUR' },
  { code: 'MF', name: 'Saint Martin', currency: 'EUR' },
  { code: 'SX', name: 'Sint Maarten', currency: 'ANG' },
  { code: 'CW', name: 'Curaçao', currency: 'ANG' },
  { code: 'AW', name: 'Aruba', currency: 'AWG' },
  { code: 'BQ', name: 'Caribbean Netherlands', currency: 'USD' },
  { code: 'TC', name: 'Turks and Caicos Islands', currency: 'USD' },
  { code: 'VG', name: 'British Virgin Islands', currency: 'USD' },
  { code: 'VI', name: 'U.S. Virgin Islands', currency: 'USD' },
  { code: 'KY', name: 'Cayman Islands', currency: 'KYD' },
  { code: 'BM', name: 'Bermuda', currency: 'BMD' },
  { code: 'MS', name: 'Montserrat', currency: 'XCD' },
  { code: 'AI', name: 'Anguilla', currency: 'XCD' },
  { code: 'AG', name: 'Antigua and Barbuda', currency: 'XCD' },
  { code: 'DM', name: 'Dominica', currency: 'XCD' },
  { code: 'LC', name: 'Saint Lucia', currency: 'XCD' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', currency: 'XCD' },
  { code: 'KN', name: 'Saint Kitts and Nevis', currency: 'XCD' },
  { code: 'BB', name: 'Barbados', currency: 'BBD' },
  { code: 'TT', name: 'Trinidad and Tobago', currency: 'TTD' },
  { code: 'JM', name: 'Jamaica', currency: 'JMD' },
  { code: 'BS', name: 'Bahamas', currency: 'BSD' },
  { code: 'CU', name: 'Cuba', currency: 'CUP' },
  { code: 'HT', name: 'Haiti', currency: 'HTG' },
  { code: 'DO', name: 'Dominican Republic', currency: 'DOP' },
  { code: 'PR', name: 'Puerto Rico', currency: 'USD' },
  { code: 'CR', name: 'Costa Rica', currency: 'CRC' },
  { code: 'PA', name: 'Panama', currency: 'PAB' },
  { code: 'SV', name: 'El Salvador', currency: 'USD' },
  { code: 'GT', name: 'Guatemala', currency: 'GTQ' },
  { code: 'HN', name: 'Honduras', currency: 'HNL' },
  { code: 'NI', name: 'Nicaragua', currency: 'NIO' },
  { code: 'BZ', name: 'Belize', currency: 'BZD' },
  { code: 'MX', name: 'Mexico', currency: 'MXN' },
  { code: 'GL', name: 'Greenland', currency: 'DKK' },
  { code: 'IS', name: 'Iceland', currency: 'ISK' },
  { code: 'FO', name: 'Faroe Islands', currency: 'DKK' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', currency: 'NOK' },
  { code: 'AX', name: 'Åland Islands', currency: 'EUR' },
  { code: 'EE', name: 'Estonia', currency: 'EUR' },
  { code: 'LV', name: 'Latvia', currency: 'EUR' },
  { code: 'LT', name: 'Lithuania', currency: 'EUR' },
  { code: 'MD', name: 'Moldova', currency: 'MDL' },
  { code: 'BY', name: 'Belarus', currency: 'BYN' },
  { code: 'GE', name: 'Georgia', currency: 'GEL' },
  { code: 'AM', name: 'Armenia', currency: 'AMD' },
  { code: 'AZ', name: 'Azerbaijan', currency: 'AZN' },
  { code: 'KZ', name: 'Kazakhstan', currency: 'KZT' },
  { code: 'UZ', name: 'Uzbekistan', currency: 'UZS' },
  { code: 'TM', name: 'Turkmenistan', currency: 'TMT' },
  { code: 'KG', name: 'Kyrgyzstan', currency: 'KGS' },
  { code: 'TJ', name: 'Tajikistan', currency: 'TJS' },
  { code: 'MN', name: 'Mongolia', currency: 'MNT' },
  { code: 'AF', name: 'Afghanistan', currency: 'AFN' },
  { code: 'IR', name: 'Iran', currency: 'IRR' },
  { code: 'IQ', name: 'Iraq', currency: 'IQD' },
  { code: 'SY', name: 'Syria', currency: 'SYP' },
  { code: 'JO', name: 'Jordan', currency: 'JOD' },
  { code: 'LB', name: 'Lebanon', currency: 'LBP' },
  { code: 'PS', name: 'Palestine', currency: 'ILS' },
  { code: 'KW', name: 'Kuwait', currency: 'KWD' },
  { code: 'QA', name: 'Qatar', currency: 'QAR' },
  { code: 'BH', name: 'Bahrain', currency: 'BHD' },
  { code: 'OM', name: 'Oman', currency: 'OMR' },
  { code: 'AE', name: 'United Arab Emirates', currency: 'AED' },
  { code: 'YE', name: 'Yemen', currency: 'YER' },
  { code: 'AZ', name: 'Azerbaijan', currency: 'AZN' },
  { code: 'TM', name: 'Turkmenistan', currency: 'TMT' },
  { code: 'UZ', name: 'Uzbekistan', currency: 'UZS' },
  { code: 'KG', name: 'Kyrgyzstan', currency: 'KGS' },
  { code: 'TJ', name: 'Tajikistan', currency: 'TJS' },
  { code: 'MN', name: 'Mongolia', currency: 'MNT' },
  { code: 'HK', name: 'Hong Kong', currency: 'HKD' },
  { code: 'MO', name: 'Macau', currency: 'MOP' },
  { code: 'TW', name: 'Taiwan', currency: 'TWD' },
  { code: 'LA', name: 'Laos', currency: 'LAK' },
  { code: 'KH', name: 'Cambodia', currency: 'KHR' },
  { code: 'MM', name: 'Myanmar', currency: 'MMK' },
  { code: 'LK', name: 'Sri Lanka', currency: 'LKR' },
  { code: 'NP', name: 'Nepal', currency: 'NPR' },
  { code: 'BT', name: 'Bhutan', currency: 'BTN' },
  { code: 'MV', name: 'Maldives', currency: 'MVR' },
  { code: 'TL', name: 'Timor-Leste', currency: 'USD' },
  { code: 'PG', name: 'Papua New Guinea', currency: 'PGK' },
  { code: 'FJ', name: 'Fiji', currency: 'FJD' },
  { code: 'SB', name: 'Solomon Islands', currency: 'SBD' },
  { code: 'VU', name: 'Vanuatu', currency: 'VUV' },
  { code: 'NC', name: 'New Caledonia', currency: 'XPF' },
  { code: 'PF', name: 'French Polynesia', currency: 'XPF' },
  { code: 'WS', name: 'Samoa', currency: 'WST' },
  { code: 'TO', name: 'Tonga', currency: 'TOP' },
  { code: 'TV', name: 'Tuvalu', currency: 'AUD' },
  { code: 'KI', name: 'Kiribati', currency: 'AUD' },
  { code: 'NR', name: 'Nauru', currency: 'AUD' },
  { code: 'FM', name: 'Micronesia', currency: 'USD' },
  { code: 'MH', name: 'Marshall Islands', currency: 'USD' },
  { code: 'PW', name: 'Palau', currency: 'USD' },
  { code: 'CK', name: 'Cook Islands', currency: 'NZD' },
  { code: 'NU', name: 'Niue', currency: 'NZD' },
  { code: 'TK', name: 'Tokelau', currency: 'NZD' },
  { code: 'WF', name: 'Wallis and Futuna', currency: 'XPF' },
  { code: 'AS', name: 'American Samoa', currency: 'USD' },
  { code: 'GU', name: 'Guam', currency: 'USD' },
  { code: 'MP', name: 'Northern Mariana Islands', currency: 'USD' },
  { code: 'UM', name: 'U.S. Minor Outlying Islands', currency: 'USD' },
];

export function getAvailableCountries() {
  return countries;
} 