export const industryThemes = {
  retail: { primaryColor: '#0070f3', secondaryColor: '#fff', darkMode: false, logo: '/logos/retail.png' },
  healthcare: { primaryColor: '#900', secondaryColor: '#f5f5f5', darkMode: false, logo: '/logos/healthcare.png' },
  finance: { primaryColor: '#0a0', secondaryColor: '#fff', darkMode: true, logo: '/logos/finance.png' },
  manufacturing: { primaryColor: '#333', secondaryColor: '#eee', darkMode: false, logo: '/logos/manufacturing.png' },
  education: { primaryColor: '#2d7ff9', secondaryColor: '#fff', darkMode: false, logo: '/logos/education.png' },
  technology: { primaryColor: '#222', secondaryColor: '#e0e0e0', darkMode: true, logo: '/logos/technology.png' },
  logistics: { primaryColor: '#f90', secondaryColor: '#fff', darkMode: false, logo: '/logos/logistics.png' },
  agriculture: { primaryColor: '#4caf50', secondaryColor: '#fff', darkMode: false, logo: '/logos/agriculture.png' },
  energy: { primaryColor: '#ffb300', secondaryColor: '#fff', darkMode: false, logo: '/logos/energy.png' },
  hospitality: { primaryColor: '#ff7043', secondaryColor: '#fff', darkMode: false, logo: '/logos/hospitality.png' },
  real_estate: { primaryColor: '#607d8b', secondaryColor: '#fff', darkMode: false, logo: '/logos/real_estate.png' },
  media: { primaryColor: '#e040fb', secondaryColor: '#fff', darkMode: false, logo: '/logos/media.png' },
  transportation: { primaryColor: '#00bcd4', secondaryColor: '#fff', darkMode: false, logo: '/logos/transportation.png' },
  construction: { primaryColor: '#ff9800', secondaryColor: '#fff', darkMode: false, logo: '/logos/construction.png' },
  government: { primaryColor: '#263238', secondaryColor: '#fff', darkMode: false, logo: '/logos/government.png' },
  nonprofit: { primaryColor: '#43a047', secondaryColor: '#fff', darkMode: false, logo: '/logos/nonprofit.png' },
  professional_services: { primaryColor: '#3f51b5', secondaryColor: '#fff', darkMode: false, logo: '/logos/professional_services.png' },
  food_beverage: { primaryColor: '#ff5722', secondaryColor: '#fff', darkMode: false, logo: '/logos/food_beverage.png' },
  telecommunications: { primaryColor: '#009688', secondaryColor: '#fff', darkMode: false, logo: '/logos/telecommunications.png' },
  automotive: { primaryColor: '#607d8b', secondaryColor: '#fff', darkMode: false, logo: '/logos/automotive.png' },
  pharmaceuticals: { primaryColor: '#8bc34a', secondaryColor: '#fff', darkMode: false, logo: '/logos/pharmaceuticals.png' },
}; 